### ISSUE TITLE
Minio doesn't start with tmpfs-backed tempdir

### ISSUE THREAD

**Issue by maleadt** [JuliaServices/CloudBase.jl#14]
My `/tmp` is backed by `tmpfs`, which minio doesn't like: https://github.com/minio/minio/issues/13818

This results in:

```
Unable to use the drive /tmp/jl_Sh06ZG: invalid argument

API: SYSTEM()
Time: 15:13:10 UTC 09/14/2022
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       6: /workspace/srcdir/minio/internal/logger/logger.go:270:logger.LogIf()
       5: /workspace/srcdir/minio/cmd/prepare-storage.go:242:cmd.connectLoadInitFormats()
       4: /workspace/srcdir/minio/cmd/prepare-storage.go:282:cmd.waitForFormatErasure()
       3: /workspace/srcdir/minio/cmd/erasure-server-pool.go:66:cmd.newErasureServerPools()
       2: /workspace/srcdir/minio/cmd/server-main.go:679:cmd.newObjectLayer()
       1: /workspace/srcdir/minio/cmd/server-main.go:529:cmd.serverMain()
```

I guess this worked before because of using Scratch.jl (https://github.com/JuliaServices/CloudBase.jl/pull/12).

**Comment by quinnj** [comment]
@maleadt, should I revert that PR and go back to scratch? Or did you find a work-around?

**Comment by maleadt** [comment]
I can work around this for the BugReporting.jl tests, https://github.com/JuliaLang/BugReporting.jl/blob/f198a3506bd9b8e20a0203720be43d1be81f5690/test/rr.jl#L105, but I guess this may trip up other users. Or PkgEval, so maybe the CloudStore.jl tests should use a scratch directory?

**Comment by maleadt** [comment]
What exactly was the problem with PackageCompiler? Can't you use a temp dir in `~/.cache` (on Linux)? It'd be nice to have this fixed, because now Cloud* are going to fail tests on PkgEval because of this.

EDIT: actually, PkgEval uses Sandbox which uses tmpfs for almost everything. So it seems we are SOL.

EDIT2: *actually*, this looks like a bug in minio. single-node should work without O_DIRECT, i.e., should support a tmpfs. I'll file a bug: https://github.com/minio/minio/issues/15733

**Comment by quinnj** [comment]
@maleadt, sorry for the slow reply; what's the status here? Should I revert or should we keep it as-is?

**Comment by maleadt** [comment]
No, this can be closed. Turned out to be an upstream bug, which got fixed, and the JLLs bumped.
